module.exports = {


    farequote:{
    locate_review_your_flights :"//h1[text()=' Review your flights ']",
    locate_validate_passenger_page : "//h1[text()=' Passenger details ']",
    locate_apply_eVoucher_button : "//*[text()=' ADD ']/..",
    locate_add_email_for_voucher : "//span[text()='Email address']/../following-sibling::input",
    locate_add_lastName_for_voucher : "//span[text()='Last name']/../following-sibling::input",
    locate_add_eVoucher_code : "//span[text()='eVoucher code']/../following-sibling::input",
    locate_apply_voucher_button : "//span[text()=' Apply ']",
    locate_eVoucher_Link : "//span[text()=' ADD ']",
    locate_save_with_avios_button : ".login-wrapper > ba-button",
    locate_enter_ec_membership : "(//*[text()='Email / Username'])[2]",
    locate_enter_password : "(//*[text()='Password'])[2]",
    locate_click_log_in_button : "(//*[text()='Sign in'])[2]",
    locate_disability_assistance_button : "//a[text()='Disability assistance']",
    locate_hold_booking_card : "//*[text()=' Hold your flights ']/../..",
    locate_hold_booking_heading : "//*[text()=' Hold your flights ']",
    locate_hold_booking_button : "//*[contains(text(),'Hold your flights for')]",
    locate_baHotelOffer : "//*[@id='bahHotelOffer']",
    locate_baCarOffer : "//*[@id='bahCarOffer']",
    locate_breakdown_table_dropdown : ".details__icon.hydrated",
    locate_total_price : "//*[@data-qa='total-price']/h2",
    locate_yourfairconditions_dropdown : "#ba-accordion-1-button",
    locate_yourBaggageallowance_dropdown :"#ba-accordion-2-button > span > span",
    locate_foodanddrink_dropdown : "//*[@id='mealInfo']",
    locate_price_breakdown_table : ".details",
    locate_air_passenger_duty_for_YA : "(//*[contains(text(),'Young Adult')])[1]/../tbody[1]/tr[3]/td[2]",
    locate_air_passenger_duty_for_Adult : "(//*[contains(text(),' Adult ')])[1]/../tbody[1]/tr[3]/td[2]",

    //FareQuote Page
    locate_hold_booking_summary_page_price : "//*[contains(text(),'TOTAL')]/following-sibling::ba-content/h2",
    locate_hold_booking_price_and_duration : "//*[contains(text(),'Hold your flights for')]/preceding-sibling::p",
    locate_hold_booking_price_paymentPage : "//*[contains(text(),' Total ')]/following-sibling::ba-content/span",
    locate_hold_booking_page_title_paxPage : "(//*[text()='Hold Booking'])[1]",
    locate_hold_booking_page_heading_paxPage : "[class='heading-md']",
    locate_termsAndConditionLink : "//button[contains(text(),'Terms and Conditions')]",
    locate_termsAndConditionHeading : "#ba-modal-1-title",
    locate_flight_itinerary_button : "(//*[contains(text(),' flight details')])[1]",
    locate_flight_itinerary_flightNumber : ".carrier-details div:nth-child(2)",
    locate_flight_itinerary_travelClass : ".carrier-details div:nth-child(4)",
    locate_flight_itinerary_depart_airport : "(//*[contains(text(),'Terminal')]/preceding-sibling::span)[1]",
    locate_flight_itinerary_arrival_airport : ".timeline-flight-details:nth-child(1) li:nth-child(3) > .timeline-flight-details-airport > span:nth-child(1)",
    locate_flight_itinerary_depart_date_and_time : "(//*[contains(text(),'Terminal')]/../following-sibling::span)[1]",
    locate_flight_itinerary_arrival_date_and_time : ".timeline-flight-details li:nth-child(3) .timeline-flight-details-time",
    locate_flight_details_close_popup : ".is-open .close",
    locate_more_fare_options_pod : "//app-fare-options",
    locate_more_fare_options_table : ".fare-options-attribute-table:last-child",
    locate_more_fare_options_table_header : ".fare-options-attribute-table:last-child thead .cabin-header-text",
    locate_more_fare_options_table_rows_feature : ".fare-options-attribute-table:last-child .accessibility-header",
    locate_more_fare_options_table_rows_feature_value : ".fare-options-attribute-table td:not([class*=colheader]):nth-child(2)",
    locate_see_your_breakdown : "details:nth-child(1) > summary:nth-child(1) > span:nth-child(1)",
    locate_back_to_flight_selection : ".back-link",

    //HBFF Summary Page
    locate_flight_details_pod : ".trip-summary-wrapper .flight-details",
    locate_flight_itinerary_depart_airport_summaryPage : "(//*[contains(text(),'terminal')]/preceding-sibling::span)[1]",
    locate_flight_itinerary_arrival_airport_summaryPage : ".summary-table tr:nth-child(2) td:nth-child(3) > span:nth-child(1)",
    locate_flight_itinerary_depart_date_summaryPage : "//*[contains(text(),'More details')]/../../preceding-sibling::div/span",
    locate_flight_itinerary_arrival_date_summaryPage : "//*[contains(text(),'Arrives')]",
    locate_flight_itinerary_travelClass_summaryPage : ".trip-summary-cabin span:nth-child(2)",
    locate_flight_itinerary_depart_time_summaryPage : "//*[contains(text(),'Flight departing at')]/..",
    locate_flight_itinerary_arrival_time_summaryPage : "(//*[contains(text(),'Flight arriving at')]/..)[1]",
    locate_flight_more_details_link : "//*[contains(text(),'More details')]",
    locate_flight_itinerary_flightNumber_summaryPage : "//*[contains(text(),' Flight Details')]/../following-sibling::div/span",
    locate_HBFF_duration : "//*[contains(text(),'Hold flight')]",
    locate_disability_Pagetitle : "h1[class = 'pageTitle dark']",
    locate_airport_mismatch_continue_button : "[data-qa='airport-mismatch-continue-button']",

    locate_hold_booking_page_title : "(//*[text()='Hold Booking'])[1]",
    locate_hold_booking_page_heading : "[class='heading-md']",
    locate_show_your_journey_button :"//*[text()=' Show your journey ']",
    locate_title_input_box : "//*[text()='Title']",
    locate_first_name_input_box : "//*[text()='First name']",
    locate_last_name_input_box : "//*[text()='Last name']",
    locate_email_address_input_box : "//*[text()='Email address (for e-ticket receipt)']",
    locate_continue_button : "//*[text()=' Continue ']",
    locate_your_journey_box : "//*[text()=' Your journey ']/..",
    locate_price_summary : "[class='price-summary']",
    locate_first_name_passport : "#pax0-firstName-native",
    locate_last_name_passport : "#pax0-lastName-native",
    locate_email_passport : "#ba-input-8",
    locate_phone_passport : "#ba-input-9",
    locate_pax_continue_btn : "#paxContinue"
    }
}
