module.exports = {


    paymentPage:{

  locate_whospaying_dropdown : "//*[contains(text(),'paying')]/../following-sibling::select",
  locate_country_dropdown : "((//*[@class='payment-details-wrapper ng-star-inserted'])/div/following::ba-select/select)[1]",
  locate_USA_State : "((//*[@class='payment-details-wrapper ng-star-inserted'])/div/following::ba-select/select)[2]",
  locate_use_new_card_radio_btn : "//input[@id='card-payment']",
  locate_paypal_radio_btn : "//input[@id='paypal']",
  locate_use_new_card_text : "//*[text()='Use new card']",
  locate_text_box_card_number : "//iframe[starts-with(@id, 'securefields') and (@title='Card number') ]",
  locate_text_box_CVV : "//iframe[starts-with(@id, 'securefields') and @title='CVV' ]",
  locate_text_Card_month_expiry : "//input[@placeholder='MM']",
  locate_text_Card_Year_expiry : "//input[@placeholder='YY']",
  locate_text_address1 : "//input[@id='address-line1']",
  locate_text_address2 : "//input[@id='address-line2']",
  locate_text_address3 : "//input[@id='address-line3']",
  locate_text_postal_code : "//input[@id='postal-code']",
  locate_agree_pay_btn : "//*[contains(text(),' Agree')]",
  locate_cardType_logo : "//img[@class='card-image']",
  locate_secure_payment_with_PWD : "//iframe[contains(@title, 'Bank Authentication')]",
  locate_secure_payment_submit_btn : "//input[@type='password']/following::b[2]",
  locate_old_flow_payment_method_dropdown : "//*[text()='Payment method']/../..//following::select",
  locate_old_flow_personal_card_text : "//*[text()='Personal Card']",
  locate_old_flow_country_dropdown : "(//select[@class='sc-ba-select sc-ba-select-s'])[3]",
  locate_old_flow_Card_number_text_field : "//*[text()='Card number']",
  locate_old_flow_CVV_number :"//*[@id='cc-csc']",
  locate_mmb_type_of_card_dropdown :"//*[@id='CardSchemeCode1']",
  locate_mmb_card_number : "//*[@id='CardNumber1']",
  locate_mmb_expiry_month : "//*[@id='ExpiryDateMonth1']",
  locate_mmb_expiry_year : "//*[@id='ExpiryDateYear1']",
  locate_mmb_security_number : "//*[@id='CSCNumber1']",
  locate_mmb_address_line1 : "//*[@id='AddressLine1']",
  locate_mmb_address_line2 : "//*[@id='AddressLine2']",
  locate_mmb_postcode : "//*[@id='PostalCode']",
  locate_mmb_submit_button : "//*[@id='submitButton']",
  locate_final_payment : "//*[contains(text(),'TOTAL')]/..//h2",
  locate_invalid_cvv_error_text : "//*[@id='cvv-error']",
  locate_payInPersoOption : "//*[text()='Pay in person']/..",
  locate_Address_Error_Msg_Line1 : "//*[@id='address-line1-error']",
  locate_Address_Error_Msg_Line2 : "//*[@id='address-line2-error']",
  locate_Postalcode_Error_Msg : '#postal-code-error > span',
  locate_missing_card_exp_message : "//*[text()='Expiry date']/../following-sibling::p/span",
  locate_paymentCard_authorisation_text : "//h1[normalize-space()='Payment card authorisation']",
  locate_thirdPartyPayer_firstName : "//*[contains(text(),'First')]/../../input",
  locate_thirdPartyPayer_lastName : "//*[contains(text(),'last')]/../../input",
  locate_thirdPartyPayer_email : "(//*[contains(text(),'e-ticket')]/../../input)[1]",
  locate_thirdPartyPayer_title : "//*[contains(text(),'Title')]/../following-sibling::select",
  locate_available_Payment_Type : "//div[@class='payment-logos']/img",
  locate_CardNo_Error_Msg             :"//*[@id='card-number-error']",
  locate_Address_Error_Msg_Line1 : "//*[@id='address-line1-error']",
  locate_Address_Error_Msg_Line2 : "//*[@id='address-line2-error']",
  locate_Postalcode_Error_Msg : '#postal-code-error > span',
  locate_missing_card_exp_message : "//*[text()='Expiry date']/../following-sibling::p/span",
  locate_paymentCard_authorisation_text : "//h1[normalize-space()='Payment card authorisation']",
  locate_CardNo_Error_Msg             : "//*[@id='card-number-error']",
  locate_thirdPartyPayer_firstName : "//*[contains(text(),'First')]/../../input",
  locate_thirdPartyPayer_lastName : "//*[contains(text(),'last')]/../../input",
  locate_thirdPartyPayer_email : "(//*[contains(text(),'e-ticket')]/../../input)[1]",
  locate_thirdPartyPayer_title : "//*[contains(text(),'Title')]/../following-sibling::select",
  locate_available_Payment_Type : "//div[@class='payment-logos']/img",
  locate_add_business_loyality_programme : ".details__summary",
  locate_select_business_loyality_programme : "//span[text()='Business loyalty programme']",
  locate_enter_membership_Number : "div #business-loyalty-number",
  locate_headerId:"//*[@id='global-header']/div/span",
  locate_creditCardOffer_make_payment_btn:"ba-button > span",
  locate_Surcharges:"//div[@class='surcharge item-description bold ng-tns-c70-41 ng-star-inserted']",
  locate_ba_better_world_heading:"(//h2[@class='ba-c-content__summary'])[2]",
  locate_donation_radio : ".sc-ba-radio[id='2']"
   }
}